<?php

namespace TimesheetBundle\Repository;

/**
 * TimesheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimesheetRepository extends \Doctrine\ORM\EntityRepository
{
}
